version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    container_name: teslodb
    volumes:
      - psql:/var/lib/postgresql/data
volumes:
  psql: